// resources/js/Pages/Auth/TwoFactorChallenge.svelte
<script>

// resources/js/Pages/Auth/Login.svelte

    import { logData } from '@resources-js/testing';

    import { onMount, tick } from 'svelte';
    import { Link } from "@inertiajs/svelte";
    import { t } from 'svelte-i18n';

    import { useForm } from "@inertiajs/svelte";
    import GuestLayout from "@layouts/Guest.svelte";

    // Components > Branding
    import AuthenticationCard from '@components/Auth/Card.svelte';
    import AuthenticationLogo from '@components/Auth/Logo.svelte';

    // Components >Fields
    import Button from '@components/UI/Buttons/Button.svelte';
    import FieldCheckbox from '@components/Fields/Checkbox.svelte';
    import FieldSwitch from '@components/Fields/Switch.svelte';
    import FieldText from '@components/Fields/Text.svelte';
    import FieldPassword from '@components/Fields/Password.svelte';

    // Components > Forms
    import ValidationErrors from '@components/Forms/ValidationErrors.svelte';

    let recovery = false;
    let codeInput, recoveryCodeInput;

    const toggleRecovery = async () => {
        recovery = !recovery;
        await tick();

        if (recovery) {
            recoveryCodeInput.focus();
            form.code = '';
        } else {
            codeInput.focus();
            form.recovery_code = '';
        }
    };


    let form = useForm({
        code: '',
        recovery_code: '',
    });

    const submit = () => {
        // Log the form data on submit
        ray(form.data()).label('Form Data on Submit');

        $form.post(route('two-factor.login'), {
            onSubmit: () => {
                //logData(form.data(), 'Form Data Submitted');
                $form.reset('password'); // Reset the password field
            },
            onSuccess: () => {
                //logData(form.data(), 'Form Data Submitted');
                console.log('Login successful');
            },
            onError: (errors) => {
                ray(errors).label('Form Errors');
                console.error('Login failed:', errors);
            },
        });
    };


</script>

<svelte:head>
    <title>{$t('Two-factor Confirmation')}</title>
</svelte:head>

<GuestLayout>

    <AuthenticationCard>

        <AuthenticationLogo slot="logo" />

        <ValidationErrors errors={Object.values($form.errors)} />

        <p class="fw-light fs-8 text-center p-3 py-1">
            {#if !recovery}
            {$t('Please confirm access to your account by entering the authentication code provided by your authenticator application.')}
            {:else}
            {$t('Please confirm access to your account by entering one of your emergency recovery codes.')}
            {/if}
        </p>

        <form on:submit|preventDefault={submit} class="form-auth text-center">
        {#if !recovery}
            <FieldText 
                form={$form} 
                id="code"
                ref="codeInput"
                inputmode="numeric"
                autofocus
                autocomplete="one-time-code"
                label="{$t('Code')}" 
            />
        {:else}
            <FieldText 
                form={$form} 
                id="recovery_code"
                ref="recoveryCodeInput"
                autocomplete="one-time-code"
                label="{$t('Recovery Code')}" 
            />
        {/if}

            <div class="flex items-center justify-end mt-4">
                <Button type="submit" disabled={$form.processing} cssClass="btn-lg btn-primary w-100 py-2 mb-2">
                    {$t('Log In')}
                </Button>
                <Button 
                    type="button"
                    cssClass="fs-8 fw-light"
                    on:click={toggleRecovery}
                >
                    {#if !recovery}
                        {$t('Use a recovery code')}
                    {:else}
                        {$t('Use an authentication code')}
                    {/if}
                    </Button>
            </div>
        </form>

    </AuthenticationCard>

</GuestLayout>

// resources/js/Pages/Auth/TwoFactorChallenge.vue
<script setup>
import { nextTick, ref } from 'vue';
import { Head, useForm } from '@inertiajs/vue3';
import AuthenticationCard from '@/Components/Vue/AuthenticationCard.vue';
import AuthenticationCardLogo from '@/Components/Vue/AuthenticationCardLogo.vue';
import InputError from '@/Components/Vue/InputError.vue';
import InputLabel from '@/Components/Vue/InputLabel.vue';
import PrimaryButton from '@/Components/Vue/PrimaryButton.vue';
import TextInput from '@/Components/Vue/TextInput.vue';

const recovery = ref(false);

const form = useForm({
    code: '',
    recovery_code: '',
});

const recoveryCodeInput = ref(null);
const codeInput = ref(null);

const toggleRecovery = async () => {
    recovery.value ^= true;

    await nextTick();

    if (recovery.value) {
        recoveryCodeInput.value.focus();
        form.code = '';
    } else {
        codeInput.value.focus();
        form.recovery_code = '';
    }
};

const submit = () => {
    form.post(route('two-factor.login'));
};
</script>

<template>
    <Head title="Two-factor Confirmation" />

    <AuthenticationCard>
        <template #logo>
            <AuthenticationCardLogo />
        </template>

        <div class="mb-4 text-sm text-gray-600 dark:text-gray-400">
            <template v-if="! recovery">
                Please confirm access to your account by entering the authentication code provided by your authenticator application.
            </template>

            <template v-else>
                Please confirm access to your account by entering one of your emergency recovery codes.
            </template>
        </div>

        <form @submit.prevent="submit">
            <div v-if="! recovery">
                <InputLabel for="code" value="Code" />
                <TextInput
                    id="code"
                    ref="codeInput"
                    v-model="form.code"
                    type="text"
                    inputmode="numeric"
                    class="mt-1 block w-full"
                    autofocus
                    autocomplete="one-time-code"
                />
                <InputError class="mt-2" :message="form.errors.code" />
            </div>

            <div v-else>
                <InputLabel for="recovery_code" value="Recovery Code" />
                <TextInput
                    id="recovery_code"
                    ref="recoveryCodeInput"
                    v-model="form.recovery_code"
                    type="text"
                    class="mt-1 block w-full"
                    autocomplete="one-time-code"
                />
                <InputError class="mt-2" :message="form.errors.recovery_code" />
            </div>

            <div class="flex items-center justify-end mt-4">
                <button type="button" class="text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 underline cursor-pointer" @click.prevent="toggleRecovery">
                    <template v-if="! recovery">
                        Use a recovery code
                    </template>

                    <template v-else>
                        Use an authentication code
                    </template>
                </button>

                <PrimaryButton class="ms-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Log in
                </PrimaryButton>
            </div>
        </form>
    </AuthenticationCard>
</template>
